//@version=4
study(title="My Relative Strength Index", shorttitle="MRSI")

///////////////////////////////////////////////////////////
// Input
///////////////////////////////////////////////////////////
rsiLength = input(30, minval=1, title="RSI Length")
forceShowBTCHashrate = input(false, title="Show Hashrate below Daily")
hashRateVisibility = input("Hidden", title="Bitcoin Hashrate visibility :", options=['Hidden','Any TF', 'Higher TF', 'Lower TF'])

var isBtcUsd = syminfo.ticker == "BTCUSD"
var isHigherTimeFrame = timeframe.isdaily or timeframe.isweekly or timeframe.ismonthly
var showHTFBtcIndicators = isBtcUsd and isHigherTimeFrame
showHashrate = false
if (isHigherTimeFrame and (hashRateVisibility == "Any TF" or hashRateVisibility == "Higher TF"))
    showHashrate := true
else if (isHigherTimeFrame == false and (hashRateVisibility == "Any TF" or hashRateVisibility == "Lower TF"))
    showHashrate := true

var scaleAdujster = showHashrate ? 58 : 0

///////////////////////////////////////////////////////////
// RSI Calculation
///////////////////////////////////////////////////////////

// Over bought - Over sold values
rsiValueTop_top = if (timeframe.ismonthly)
    92
else if (timeframe.isweekly)
    90
else if (timeframe.isdaily)
    75
else if (timeframe.period == '240')
    72
else if (timeframe.period == '15')
    73
rsiValueTop_bottom = if (timeframe.ismonthly)
    84
else if (timeframe.isweekly)
    83
else if (timeframe.isdaily)
    72
else if (timeframe.period == '240')
    68
else if (timeframe.period == '15')
    70
rsiValueBottom_top = if (timeframe.ismonthly)
    52
else if (timeframe.isweekly)
    48
else if (timeframe.isdaily)
    45
else if (timeframe.period == '240')
    39
else if (timeframe.period == '15')
    32
rsiValueBottom_bottom = if (timeframe.ismonthly)
    49
else if (timeframe.isweekly)
    42
else if (timeframe.isdaily)
    39
else if (timeframe.period == '240')
    35
else if (timeframe.period == '15')
    30


up = rma(max(change(close), 0), rsiLength)
down = rma(-min(change(close), 0), rsiLength)
rsi = (down == 0 ? 100 : up == 0 ? 0 : 100 - (100 / (1 + up / down))) - scaleAdujster

//
//
//

fastMA = ema(high, 12)
slowMA = ema(high, 26)
rsiForColor = if (timeframe.isminutes and timeframe.period == '1')
    rsi(close, 14)
else if (timeframe.isminutes and timeframe.period == '15')
    rsi(close, 14)
else 
    rsi(close, 30)
    
macd = fastMA - slowMA
macdOverExtended = if (timeframe.isweekly)
    if (rsiForColor > 60)
        100 + (high - macd) / high * 100 <= 187.5 ? 100 + (high - macd) / high * 100 : 0
    else
        100 + (high - macd) / high * 100 >= 220 ? 100 + (high - macd) / high * 100 : 0
else if (timeframe.isdaily)
    if (rsiForColor > 60)
        100 + (high - macd) / high * 100 <= 191.5 ? 100 + (high - macd) / high * 100 : 0
    else
        100 + (high - macd) / high * 100 >= 206 ? 100 + (high - macd) / high * 100 : 0
else if (timeframe.isminutes and timeframe.period == '240') // DONE
    if (rsiForColor > 60)
        100 + (high - macd) / high * 100 <= 196.8 ? 100 + (high - macd) / high * 100 : 0
    else
        100 + (high - macd) / high * 100 >= 203 ? 100 + (high - macd) / high * 100 : 0
else if (timeframe.isminutes and timeframe.period == '15') // DONE
    if (rsiForColor > 60)
        100 + (high - macd) / high * 100 <= 199 ? 100 + (high - macd) / high * 100 : 0
    else
        100 + (high - macd) / high * 100 >= 201 ? 100 + (high - macd) / high * 100 : 0
else if (timeframe.isminutes and timeframe.period == '60') // TODO
    if (rsiForColor > 60)
        100 + (high - macd) / high * 100 <= 198 ? 100 + (high - macd) / high * 100 : 0
    else
        100 + (high - macd) / high * 100 >= 201.8 ? 100 + (high - macd) / high * 100 : 0
else if (timeframe.isminutes and timeframe.period == '1') // DONE
    if (rsiForColor > 60)
        100 + (high - macd) / high * 100 <= 199.8 ? 100 + (high - macd) / high * 100 : 0
    else
        100 + (high - macd) / high * 100 >= 200.5 ? 100 + (high - macd) / high * 100 : 0
else
    0

rsiLineColor = color.new(color.gray, 40)
rsiLineReversalColor = color.new(#be4fea, 0)
rsiLineWidth = 2

if (timeframe.isminutes)

    rsiValueHigh = if (timeframe.period == '1')
        70
    else if (timeframe.period == '5')
        70
    else if (timeframe.period == '15')
        70
    else if (timeframe.period == '30')
        72
    else if (timeframe.period == '60')
        69
    else if (timeframe.period == '240')
        70
    else
        na
    
    rsiValueHigher = if (timeframe.period == '1')
        74
    else if (timeframe.period == '5')
        72
    else if (timeframe.period == '15')
        73
    else if (timeframe.period == '30')
        74
    else if (timeframe.period == '60')
        72
    else if (timeframe.period == '240')
        74  
    else
        na
    
    rsiValueLow = if (timeframe.period == '1')
        30
    else if (timeframe.period == '5')
        35
    else if (timeframe.period == '15')
        32
    else if (timeframe.period == '30')
        37
    else if (timeframe.period == '60')
        34
    else if (timeframe.period == '240')
        42
    else
        na
    
    rsiValueLower = if (timeframe.period == '1')
        27
    else if (timeframe.period == '5')
        33
    else if (timeframe.period == '15')
        30
    else if (timeframe.period == '30')
        32
    else if (timeframe.period == '60')
        32
    else if (timeframe.period == '240')
        40
    else
        na

    if (rsiForColor >= rsiValueHigher and macdOverExtended > 0)
        rsiLineColor := rsiLineReversalColor
        rsiLineWidth := 4
    else if (rsiForColor >= rsiValueHigh and macdOverExtended > 0)
        rsiLineColor := rsiLineReversalColor
        rsiLineWidth := 4
    else if (rsiForColor <= rsiValueLower and macdOverExtended > 0)
        rsiLineColor := rsiLineReversalColor
        rsiLineWidth := 4
    else if (rsiForColor <= rsiValueLow and macdOverExtended > 0)
        rsiLineColor := rsiLineReversalColor
        rsiLineWidth := 4
else if (timeframe.isdaily)
    rsiValueHigh = 72
    
    rsiValueHigher = 77  
    
    rsiValueLow = 45
    
    rsiValueLower = 39

    if (rsiForColor >= rsiValueHigher and macdOverExtended > 0)
        rsiLineColor := rsiLineReversalColor
        rsiLineWidth := 4
    else if (rsiForColor >= rsiValueHigh and macdOverExtended > 0)
        rsiLineColor := rsiLineReversalColor
        rsiLineWidth := 4
    else if (rsiForColor <= rsiValueLower and macdOverExtended > 0)
        rsiLineColor := rsiLineReversalColor
        rsiLineWidth := 4
    else if (rsiForColor <= rsiValueLow and macdOverExtended > 0)
        rsiLineColor := rsiLineReversalColor
        rsiLineWidth := 4
else if (timeframe.isweekly)
    rsiValueHigh = 83
    
    rsiValueHigher = 90 
    
    rsiValueLow = 48
    
    rsiValueLower = 42

    if (rsiForColor >= rsiValueHigher and macdOverExtended > 0)
        rsiLineColor := rsiLineReversalColor
        rsiLineWidth := 4
    else if (rsiForColor >= rsiValueHigh and macdOverExtended > 0)
        rsiLineColor := rsiLineReversalColor
        rsiLineWidth := 4
    else if (rsiForColor <= rsiValueLower and macdOverExtended > 0)
        rsiLineColor := rsiLineReversalColor
        rsiLineWidth := 4
    else if (rsiForColor <= rsiValueLow and macdOverExtended > 0)
        rsiLineColor := rsiLineReversalColor
        rsiLineWidth := 4
else
    na

//
//
//

plot(rsi, "RSI", color=rsiLineColor, linewidth=2)

top_top = plot(rsiValueTop_top - scaleAdujster, style=plot.style_line, color=color.red)
top_bottom = plot(rsiValueTop_bottom - scaleAdujster, style=plot.style_line, color=color.red)
bottom_top = plot(rsiValueBottom_top - scaleAdujster, style=plot.style_line, color=color.lime)
bottom_bottom = plot(rsiValueBottom_bottom - scaleAdujster, style=plot.style_line, color=color.lime)

fill(bottom_bottom, bottom_top, color=color.lime, transp=75)
fill(top_top, top_bottom, color=color.red, transp=75)

///////////////////////////////////////////////////////////
// Hashrate Calculation
///////////////////////////////////////////////////////////

live_HR_short = security("QUANDL:BCHAIN/HRATE", "D", sma(close, 21),gaps=barmerge.gaps_off, lookahead=barmerge.lookahead_on)
live_HR_long = security("QUANDL:BCHAIN/HRATE", "D", sma(close, 105),gaps=barmerge.gaps_off, lookahead=barmerge.lookahead_on) 
hist_HR_short = security("QUANDL:BCHAIN/HRATE", "D", sma(close, 21),gaps=barmerge.gaps_off, lookahead=barmerge.lookahead_off) 
hist_HR_long = security("QUANDL:BCHAIN/HRATE", "D", sma(close, 105),gaps=barmerge.gaps_off, lookahead=barmerge.lookahead_off) 

HR_short = barstate.isrealtime ? live_HR_short : hist_HR_short
HR_long = barstate.isrealtime ? live_HR_long : hist_HR_long

delta = HR_short-HR_long
diff = (delta/HR_short)*100

plot(showHashrate ? diff : na, style=plot.style_line, color=(diff < 0 ? color.red : color.blue), title='BTC Hashrate', linewidth=2)
plot(showHashrate ? 0 : na, "Mid", color=color.olive, style=plot.style_line)