////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
//
// WE not ME (Bitcoin Indicator)
//
// Telegram: https://t.me/we_not_me
//
// David Stevens <mail.davro@gmail.com>
// 
// Donations are accepted here
// Bitcoin: 3Ph9wP4vgASFbFP9DAabZETycXY66ebA8Y
//
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
//@version=4
study("WE-Indicator", "WE", overlay=true)


// Tom Demark
showSellTDs         = input(false, title="TD Sell")
showBuyTDs          = input(false, title="TD Buy")
show1to8TDs         = input(false, title="TD 1-8")
showTDTrendlines    = input(false, title="TD Trend Lines")
showLogGrowthCurves = input(false, title="Log Growth Curves")

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
//
// RSI Visual Vertical (Green IN, Red OUT) 
//   Red for over bought, out, sell, take, profits, take a short position 
//   Green for oversold, in, buy, maybe take a long position
//
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

showVerticalHeatmap = input(false, title="Vertical Heatmap - Show/Hide")

fastMA = ema(high, 12)
slowMA = ema(high, 26)
rsi = if (timeframe.isminutes and timeframe.period == '1')
    rsi(close, 14)
else if (timeframe.isminutes and timeframe.period == '15')
    rsi(close, 14)
else 
    rsi(close, 30)
    
macd = fastMA - slowMA
macdOverExtended = if (hideMacdMatch == true)
    0
else if (timeframe.isdaily)
    100 + (high - macd) / high * 100 <= 191.5 ? 100 + (high - macd) / high * 100 : 0
else if (timeframe.isminutes and timeframe.period == '240') // DONE
    if (rsi > 60)
        100 + (high - macd) / high * 100 <= 196.8 ? 100 + (high - macd) / high * 100 : 0
    else
        100 + (high - macd) / high * 100 >= 203 ? 100 + (high - macd) / high * 100 : 0
else if (timeframe.isminutes and timeframe.period == '15') // DONE
    if (rsi > 60)
        100 + (high - macd) / high * 100 <= 199 ? 100 + (high - macd) / high * 100 : 0
    else
        100 + (high - macd) / high * 100 >= 201 ? 100 + (high - macd) / high * 100 : 0
else if (timeframe.isminutes and timeframe.period == '60') // TODO
    if (rsi > 60)
        100 + (high - macd) / high * 100 <= 198 ? 100 + (high - macd) / high * 100 : 0
    else
        100 + (high - macd) / high * 100 >= 201.8 ? 100 + (high - macd) / high * 100 : 0
else if (timeframe.isminutes and timeframe.period == '1') // DONE
    if (rsi > 60)
        100 + (high - macd) / high * 100 <= 199.8 ? 100 + (high - macd) / high * 100 : 0
    else
        100 + (high - macd) / high * 100 >= 200.5 ? 100 + (high - macd) / high * 100 : 0
else
    0

backgroundColorByRSI = if (showVerticalHeatmap == false)
    0
else if (timeframe.isminutes)

    rsiValueHigh = if (timeframe.period == '1')
        70
    else if (timeframe.period == '5')
        70
    else if (timeframe.period == '15')
        70
    else if (timeframe.period == '30')
        72
    else if (timeframe.period == '60')
        69
    else if (timeframe.period == '240')
        70
    else
        na
    
    rsiValueHigher = if (timeframe.period == '1')
        74
    else if (timeframe.period == '5')
        72
    else if (timeframe.period == '15')
        73
    else if (timeframe.period == '30')
        74
    else if (timeframe.period == '60')
        72
    else if (timeframe.period == '240')
        74  
    else
        na
    
    rsiValueLow = if (timeframe.period == '1')
        30
    else if (timeframe.period == '5')
        35
    else if (timeframe.period == '15')
        32
    else if (timeframe.period == '30')
        37
    else if (timeframe.period == '60')
        34
    else if (timeframe.period == '240')
        42
    else
        na
    
    rsiValueLower = if (timeframe.period == '1')
        27
    else if (timeframe.period == '5')
        33
    else if (timeframe.period == '15')
        30
    else if (timeframe.period == '30')
        32
    else if (timeframe.period == '60')
        32
    else if (timeframe.period == '240')
        40
    else
        na

    if (rsi >= rsiValueHigher and macdOverExtended > 0)
        color.new(color.orange, 40)
    else if (rsi >= rsiValueHigh and macdOverExtended > 0)
        color.new(color.orange, 40)
    else if (rsi >= rsiValueHigher)
        color.new(color.red, 40)
    else if (rsi >= rsiValueHigh)
        color.new(color.red, 70)
    else if (rsi <= rsiValueLower and macdOverExtended > 0)
        color.new(color.blue, 40)
    else if (rsi <= rsiValueLow and macdOverExtended > 0)
        color.new(color.blue, 40)
    else if (rsi <= rsiValueLower)
        color.new(color.green, 40)
    else if (rsi <= rsiValueLow)
        color.new(color.green, 70)
else if (timeframe.isdaily)
    rsiValueHigh = 72
    
    rsiValueHigher = 77  
    
    rsiValueLow = 30
    
    rsiValueLower = 30

    if (rsi >= rsiValueHigher and macdOverExtended > 0)
        color.new(color.orange, 40)
    else if (rsi >= rsiValueHigh and macdOverExtended > 0)
        color.new(color.orange, 40)
    else if (rsi >= rsiValueHigher)
        color.new(color.red, 40)
    else if (rsi >= rsiValueHigh)
        color.new(color.red, 70)
    else if (rsi <= rsiValueLower)
        color.new(color.green, 40)
    else if (rsi <= rsiValueLow)
        color.new(color.green, 70)
else if (timeframe.isweekly)
    rsiValueHigh = 83
    
    rsiValueHigher = 90
    
    rsiValueLow = 44
    
    rsiValueLower = 42

    if (rsi >= rsiValueHigher)
        color.new(color.red, 40)
    else if (rsi >= rsiValueHigh)
        color.new(color.red, 70)
    else if (rsi <= rsiValueLower)
        color.new(color.green, 40)
    else if (rsi <= rsiValueLow)
        color.new(color.green, 70)
else
    na
bgcolor(color=backgroundColorByRSI)


////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
//
// TD Sequential 
//
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
buySignals = 0
buySignals := (close < close[4]) ? buySignals[1] == 9 ? 1 : buySignals[1] + 1 : 0

sellSignals = 0
sellSignals := (close > close[4]) ? sellSignals[1] == 9 ? 1 : sellSignals[1] + 1 : 0

BuyOrSell = max(buySignals, sellSignals)

// Commented out to save on outputs
// plotchar(showBuyTDs and show1to8TDs and buySignals and BuyOrSell == 1, char="", text="1", textcolor=color.green, location=location.belowbar, transp=40)
plotchar(showBuyTDs and show1to8TDs and buySignals and BuyOrSell == 2, char="", text="2", textcolor=color.green, location=location.belowbar, transp=40)
plotchar(showBuyTDs and show1to8TDs and buySignals and BuyOrSell == 3, char="", text="3", textcolor=color.green, location=location.belowbar, transp=40)
plotchar(showBuyTDs and show1to8TDs and buySignals and BuyOrSell == 4, char="", text="4", textcolor=color.green, location=location.belowbar, transp=40)
plotchar(showBuyTDs and show1to8TDs and buySignals and BuyOrSell == 5, char="", text="5", textcolor=color.green, location=location.belowbar, transp=40)
plotchar(showBuyTDs and show1to8TDs and buySignals and BuyOrSell == 6, char="", text="6", textcolor=color.green, location=location.belowbar, transp=40)
plotchar(showBuyTDs and show1to8TDs and buySignals and BuyOrSell == 7, char="", text="7", textcolor=color.green, location=location.belowbar, transp=40)
plotchar(showBuyTDs and show1to8TDs and buySignals and BuyOrSell == 8, char="", text="8", textcolor=color.green, location=location.belowbar, transp=20)
plotshape(showBuyTDs and buySignals and BuyOrSell == 9, text="9",color=color.green, textcolor=color.green, size=size.tiny, location=location.belowbar, transp=0)

// Commented out to save on outputs
// plotchar(showSellTDs and show1to8TDs and sellSignals and BuyOrSell == 1, char="", text="1", textcolor=color.red, location=location.abovebar, transp=40)
plotchar(showSellTDs and show1to8TDs and sellSignals and BuyOrSell == 2, char="", text="2", textcolor=color.red, location=location.abovebar, transp=40)
plotchar(showSellTDs and show1to8TDs and sellSignals and BuyOrSell == 3, char="", text="3", textcolor=color.red, location=location.abovebar, transp=40)
plotchar(showSellTDs and show1to8TDs and sellSignals and BuyOrSell == 4, char="", text="4", textcolor=color.red, location=location.abovebar, transp=40)
plotchar(showSellTDs and show1to8TDs and sellSignals and BuyOrSell == 5, char="", text="5", textcolor=color.red, location=location.abovebar, transp=40)
plotchar(showSellTDs and show1to8TDs and sellSignals and BuyOrSell == 6, char="", text="6", textcolor=color.red, location=location.abovebar, transp=40)
plotchar(showSellTDs and show1to8TDs and sellSignals and BuyOrSell == 7, char="", text="7", textcolor=color.red, location=location.abovebar, transp=40)
plotchar(showSellTDs and show1to8TDs and sellSignals and BuyOrSell == 8, char="", text="8", textcolor=color.red, location=location.abovebar, transp=20)
plotshape(showSellTDs and sellSignals and BuyOrSell == 9, text="9",color=color.red, textcolor=color.red, size=size.tiny, location=location.abovebar, transp=0)

////////////////////////////////////////////////////////////////////////////////
// TD Sequential - Trend Lines
////////////////////////////////////////////////////////////////////////////////
highest9 = highest(9)
highTrendLine = 0.0
highTrendLine := buySignals == 9 ? highest9
              : close > highTrendLine[1] ? 0
              : highTrendLine[1]
               
lowest9 = lowest(9)
lowTrendLine = 0.0
lowTrendLine := sellSignals == 9 ? lowest9
              : close < lowTrendLine[1] ? 0
              : lowTrendLine[1]

plot(showTDTrendlines and highTrendLine > 0 ? highTrendLine : na, title="Trendline", color=color.blue, style=plot.style_circles, linewidth=1, transp=0)
plot(showTDTrendlines and lowTrendLine > 0 ? lowTrendLine : na, title="Trendline", color=color.white, style=plot.style_circles, linewidth=1, transp=0)

////////////////////////////////////////////////////////////////////////////////


////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
//
// Bitcoin Log Growth Curves
//
// Features
//
// RISK Curve
// Curve Projection
//
// Inspired by @Quantadelic aka Pinescript Pleb
//
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

darkOrLight =    input("Dark", title="Dark mode or Light mode?", options=["Dark", "Light"])
showFibs =       input("Y", title="Show Fibonacci Levels?", options=["Y","N"])
showExtensions = input("Y", title="Show Curve Projections?", options=["Y","N"])
highIntercept =  input(1.06930947, title="Top Curve Intercept", step=0.001)
highSlope =      input(0.00076, title="Top Curve Slope", step=0.00001)
lowIntercept =   input(-3.0269716, title="Bottom Curve Intercept", step=0.001)
lowSlope =       input(0.001329, title="Bottom Curve Slope", step=0.00001)

// TIME CALCS
timeIndex =     time < 1279670400000 ? 3.0 : (time - 1279670400000) / 86400000
weight =        (log10(timeIndex + 10) * timeIndex * timeIndex - timeIndex) / 30000
timeDelta =     time - time[1]

// TOP OF CHANNEL INTERCEPT & SLOPE CALCS
highSlopeCum =  highSlope * timeIndex
highLogDev =    timeIndex > 2 ? log(weight) + highIntercept + highSlopeCum : na

// BOTTOM OF CHANNEL INTERCEPT & SLOPE CALCS
lowSlopeCum = lowSlope * timeIndex
LowLogDev = timeIndex > 2 ? log(weight) + lowIntercept + lowSlopeCum : na

// TOTAL CHANNEL LOG RANGE
LogRange = highLogDev - LowLogDev

// FIBONACCI LEVELS
fib9098Calc = (LogRange * 0.9098) + LowLogDev
fib8541Calc = (LogRange * 0.8541) + LowLogDev
fib7639Calc = (LogRange * 0.7639) + LowLogDev
fib618Calc  = (LogRange * 0.618) + LowLogDev
midCalc     = (LogRange * 0.5) + LowLogDev
fib382Calc  = (LogRange * 0.382) + LowLogDev
fib2361Calc = (LogRange * 0.2361) + LowLogDev
fib1459Calc = (LogRange * 0.1459) + LowLogDev
fib0902Calc = (LogRange * 0.0902) + LowLogDev

// SCALE LOG VARIABLES TO LINEAR
highDev = if (showLogGrowthCurves)
    pow(2.718281828459, highLogDev)
    
fib9098Dev = if (showLogGrowthCurves)
    showFibs == "Y" ? pow(2.718281828459, fib9098Calc) : na
    
fib8541Dev = if (showLogGrowthCurves)
    showFibs == "Y" ? pow(2.718281828459, fib8541Calc) : na
    
fib7639Dev = if (showLogGrowthCurves)
    showFibs == "Y" ? pow(2.718281828459, fib7639Calc) : na
    
fib618Dev = if (showLogGrowthCurves)
    showFibs == "Y" ? pow(2.718281828459, fib618Calc) : na
    
midDev = if (showLogGrowthCurves)
    pow(2.718281828459, midCalc)
    
fib382Dev = if (showLogGrowthCurves)
    showFibs == "Y" ? pow(2.718281828459, fib382Calc) : na
    
fib2361Dev = if (showLogGrowthCurves)
    showFibs == "Y" ? pow(2.718281828459, fib2361Calc) : na
    
fib1459Dev = if (showLogGrowthCurves)
    showFibs == "Y" ? pow(2.718281828459, fib1459Calc) : na
    
fib0902Dev = if (showLogGrowthCurves)
    showFibs == "Y" ? pow(2.718281828459, fib0902Calc) : na

lowDev = if (showLogGrowthCurves)
    pow(2.718281828459, LowLogDev)

// COLOR SCHEME
colorBullScheme = darkOrLight == "Dark" ? color(color.red) : color(color.black)
colorBearScheme = darkOrLight == "Dark" ? color(color.green) : color(color.black)

// PLOTS - Fibonacci Levels
plot(highDev, color=colorBullScheme, transp=0, title="RISK 100%")
plot(fib9098Dev, color=colorBullScheme, transp=10, title="RISK  90.98%")
plot(fib8541Dev, color=colorBullScheme, transp=20, title="RISK 85.41% ")
plot(fib7639Dev, color=colorBullScheme, transp=20, title="RISK  76.39%")
plot(fib618Dev, color=colorBullScheme, transp=0, title="RISK 61.80%")
plot(midDev, color=color.white, transp=0, title="RISK 50%")
plot(fib382Dev, color=colorBearScheme, transp=0, title="RISK 38.20%")
plot(fib1459Dev, color=colorBearScheme, transp=20, title="RISK 14.59%")
plot(fib0902Dev, color=colorBearScheme, transp=10, title="RISK 9.02%")
plot(lowDev, color=colorBearScheme, transp=0, title="RISK 0%")

// Curve Extension drawing function and helper variables
ExtenZe(_i, _slope, _intercept) =>
    TI = ((time + timeDelta *_i) -1279670400000) / 86400000
    W = (log10(TI + 10) * TI * TI - TI) / 30000
    HSC = _slope * TI
    HLD = log(W) + _intercept + HSC
    HD = pow(2.718281828459, HLD)
    HD

// VARIABLES FOR ADJUSTING LENGTH OF CURVE EXTENSIONS RELATIVE TO CHART TIME-FRAME
forLoopStep = timeframe.ismonthly == 1 ? ceil( 12 / timeframe.multiplier) : 
              timeframe.isweekly == 1 ? ceil(26 / timeframe.multiplier) : 
              timeframe.isdaily == 1 ? ceil(91 / timeframe.multiplier) : 
              (timeframe.isminutes == 1) and (timeframe.multiplier > 59) ? ceil(10080 / timeframe.multiplier) : na
forLoopMax = na(forLoopStep) ? na : forLoopStep * 13

// MID CURVE SLOPE & INTERCEPT
midSlope =      (highSlope + lowSlope) * 0.5
midIntercept =  (highIntercept + lowIntercept) * 0.5

// COLOR SCHEME
ColorSchemeProjected =   darkOrLight == "Dark" ? color(color.blue) : color(color.black)
ColorSchemeMidProjected =   darkOrLight == "Dark" ? color(color.white) : color(color.black)

// CHECK IF LAST BAR & "Show Curve Projections" IS CHECKED, THEN DRAW CURVE EXTENZES
if barstate.islast and showExtensions == "Y"
    for i = 0 to forLoopMax-1 by forLoopStep
        // line.new(time + timeDelta * i, ExtenZe(i, highSlope, highIntercept), time + timeDelta * (i + forLoopStep), ExtenZe(i + forLoopStep, highSlope, highIntercept), xloc=xloc.bar_time, color=ColorSchemeProjected)
        
        line.new(time + timeDelta * i, ExtenZe(i, highSlope, highIntercept), time + timeDelta * (i + forLoopStep), ExtenZe(i + forLoopStep, highSlope, highIntercept), xloc=xloc.bar_time, color=ColorSchemeProjected)
        line.new(time + timeDelta * i, ExtenZe(i, midSlope, midIntercept), time + timeDelta * (i + forLoopStep), ExtenZe(i + forLoopStep, midSlope, midIntercept), xloc=xloc.bar_time, color=ColorSchemeMidProjected)
        line.new(time + timeDelta * i, ExtenZe(i, lowSlope, lowIntercept), time + timeDelta * (i + forLoopStep), ExtenZe(i + forLoopStep, lowSlope, lowIntercept), xloc=xloc.bar_time, color=ColorSchemeProjected)

////////////////////////////////////////////////////////////////////////////////

// len=input(10)
// o=ema(open,len)
// c=ema(close,len)
// h=ema(high,len)
// l=ema(low,len)

// haclose = (o+h+l+c)/4
// haopen = na(haopen[1]) ? (o + c)/2 : (haopen[1] + haclose[1]) / 2
// hahigh = max (h, max(haopen,haclose))
// halow = min (l, min(haopen,haclose))

// len2=input(10)
// o2=ema(haopen, len2)
// c2=ema(haclose, len2)
// h2=ema(hahigh, len2)
// l2=ema(halow, len2)

// col=o2>c2 ? red : lime
// plotcandle(o2, h2, l2, c2, title="heikin smoothed", color=col)