// @version = 4
study("My TDI B/S GOLD 15min", shorttitle="GOLD_15min", overlay=true)

rsiPeriod = input(13, minval = 1, title = "GOLD 15min RSI Period")
buyLow = input(32, minval = 1, title = "GOLD 15min Buy Low trigger")
sellHigh = input(68, minval = 1, title = "GOLD 15min Buy Low trigger")

bandLength = 31
currentCandleClose = close
previousCandleClose = close[1]

currentRsi = rsi(currentCandleClose, rsiPeriod)
previousRsi = rsi(previousCandleClose, rsiPeriod)

previousRsiMA = sma(previousRsi, bandLength)

offset = (1.6185 * stdev(previousRsi, bandLength))

topLine = previousRsiMA + offset
bottomLine = previousRsiMA - offset
midLine = (topLine + bottomLine) / 2

fastMA = sma(previousRsi, 1)
slowMA = sma(previousRsi, 9)

buyEntry = previousRsi <= buyLow and (bottomLine - fastMA > 1) and slowMA < midLine and currentCandleClose > previousCandleClose
sellEntry = previousRsi >= sellHigh and (fastMA - topLine > 1) and slowMA > midLine and currentCandleClose < previousCandleClose and slowMA >= sellHigh

plotshape(buyEntry, style=shape.labelup,size=size.small, text="B", color=color.green, textcolor=color.white, location=location.belowbar)
plotshape(sellEntry, style=shape.labeldown,size=size.small, text="S", color=color.red, textcolor=color.white, location=location.abovebar)