//@version=4
study(title="rsi_macd_background", shorttitle="rmb", overlay=true)

///////////////////////////////////////////////////////////
// Input
///////////////////////////////////////////////////////////

userRsi = input(false, title="Use below RSI")
rsiLength = input(30, minval=1, title="RSI Length")

///////////////////////////////////////////////////////////
// RSI Calculation
///////////////////////////////////////////////////////////

rsiValue = if (userRsi)
    rsiLength
else if (timeframe.ismonthly or timeframe.isweekly)
    14
else
    30

// Over bought - Over sold values
rsiValueTop_top = if (timeframe.ismonthly)
    92
else if (timeframe.isweekly)
    90
else if (timeframe.isdaily)
    75
else if (timeframe.period == '240')
    72
else if (timeframe.period == '15')
    73
rsiValueTop_bottom = if (timeframe.ismonthly)
    84
else if (timeframe.isweekly)
    83
else if (timeframe.isdaily)
    72
else if (timeframe.period == '240')
    68
else if (timeframe.period == '15')
    70
rsiValueBottom_top = if (timeframe.ismonthly)
    52
else if (timeframe.isweekly)
    48
else if (timeframe.isdaily)
    45
else if (timeframe.period == '240')
    39
else if (timeframe.period == '15')
    32
rsiValueBottom_bottom = if (timeframe.ismonthly)
    49
else if (timeframe.isweekly)
    42
else if (timeframe.isdaily)
    39
else if (timeframe.period == '240')
    35
else if (timeframe.period == '15')
    30


up = rma(max(change(close), 0), rsiValue)
down = rma(-min(change(close), 0), rsiValue)
rsi = (down == 0 ? 100 : up == 0 ? 0 : 100 - (100 / (1 + up / down)))

//
//
//

fastMA = ema(high, 12)
slowMA = ema(high, 26)
rsiForColor = rsi(close, rsiValue)
    
macd = fastMA - slowMA
macdOverExtended = if (timeframe.isweekly)
    if (rsiForColor > 60)
        100 + (high - macd) / high * 100 <= 187.5 ? 100 + (high - macd) / high * 100 : 0
    else
        100 + (high - macd) / high * 100 >= 220 ? 100 + (high - macd) / high * 100 : 0
else if (timeframe.isdaily)
    if (rsiForColor > 60)
        100 + (high - macd) / high * 100 <= 191.5 ? 100 + (high - macd) / high * 100 : 0
    else
        100 + (high - macd) / high * 100 >= 206 ? 100 + (high - macd) / high * 100 : 0
else if (timeframe.isminutes and timeframe.period == '240') // DONE
    if (rsiForColor > 60)
        100 + (high - macd) / high * 100 <= 196.8 ? 100 + (high - macd) / high * 100 : 0
    else
        100 + (high - macd) / high * 100 >= 203 ? 100 + (high - macd) / high * 100 : 0
else if (timeframe.isminutes and timeframe.period == '15') // DONE
    if (rsiForColor > 60)
        100 + (high - macd) / high * 100 <= 199 ? 100 + (high - macd) / high * 100 : 0
    else
        100 + (high - macd) / high * 100 >= 201 ? 100 + (high - macd) / high * 100 : 0
else if (timeframe.isminutes and timeframe.period == '60') // TODO
    if (rsiForColor > 60)
        100 + (high - macd) / high * 100 <= 198 ? 100 + (high - macd) / high * 100 : 0
    else
        100 + (high - macd) / high * 100 >= 201.8 ? 100 + (high - macd) / high * 100 : 0
else if (timeframe.isminutes and timeframe.period == '1') // DONE
    if (rsiForColor > 60)
        100 + (high - macd) / high * 100 <= 199.8 ? 100 + (high - macd) / high * 100 : 0
    else
        100 + (high - macd) / high * 100 >= 200.5 ? 100 + (high - macd) / high * 100 : 0
else
    0

rsiLineColor = color.new(color.yellow, 100)
rsiLineReversalColor = color.new(#be4fea, 0)

rsiValueHigh = if (timeframe.isminutes)
    if (timeframe.period == '30')
        72
    else if (timeframe.period == '60')
        69
    else
        70
else if (timeframe.isdaily)
    72
else if (timeframe.isweekly)
    83
else
    na

rsiValueHigher = if (timeframe.isminutes)
    if (timeframe.period == '1' or timeframe.period == '30' or timeframe.period == '240')
        74
    else if (timeframe.period == '5' or timeframe.period == '60')
        72
    else if (timeframe.period == '15')
        73
    else
        70
else if (timeframe.isdaily)
    77
else if (timeframe.isweekly)
    86
else
    na

rsiValueLow = if (timeframe.isminutes)
    if (timeframe.period == '1')
        30
    else if (timeframe.period == '5')
        35
    else if (timeframe.period == '15')
        32
    else if (timeframe.period == '30')
        37
    else if (timeframe.period == '60')
        34
    else if (timeframe.period == '240')
        42
    else
        30
else if (timeframe.isdaily)
    45
else if (timeframe.isweekly)
    9
else
    na

rsiValueLower = if (timeframe.isminutes)
    if (timeframe.period == '1')
        27
    else if (timeframe.period == '5')
        33
    else if (timeframe.period == '15')
        30
    else if (timeframe.period == '30' or timeframe.period == '60')
        32
    else if (timeframe.period == '240')
        40
    else
        30
else if (timeframe.isdaily)
    39
else if (timeframe.isweekly)
    35
else
    na

weeklyClose = security(syminfo.tickerid, '1W', close)
weeklyRsi = rsi(weeklyClose, 14)
ema_21_W  = security(syminfo.tickerid, '1W', ema(close, 21))

if (rsiForColor >= rsiValueHigh)
    rsiLineColor := color.new(color.red, 70)
if (rsiForColor >= rsiValueHigher)
    rsiLineColor := color.new(color.red, 40)
if (rsiForColor >= rsiValueHigher and macdOverExtended > 0)
    rsiLineColor := color.new(color.orange, 40)
if (rsiForColor <= rsiValueLow)
    rsiLineColor := color.new(color.green, 70)
if (rsiForColor <= rsiValueLower)
    rsiLineColor := color.new(color.green, 40)
if (rsiForColor <= rsiValueLower and macdOverExtended > 0)
    rsiLineColor := color.new(color.blue, 40)
if (timeframe.isweekly)
    plotWeeklySupportAndResistance = weeklyRsi < 55 and weeklyRsi > 53 and low < ema_21_W and open > ema_21_W

    if (plotWeeklySupportAndResistance)
        rsiLineColor := color.new(color.white, 0)


bgcolor(color=rsiLineColor)