//@version=4
study(title="rsi_macd_background", shorttitle="rmb", overlay=true)

showMacdMatchOnly   = input(false, title="Show Overbought/Oversold + MACD match only")
hideMacdMatch       = input(false, title="Hide MACD match, show only overbought/oversold")

fastMA = ema(high, 12)
slowMA = ema(high, 26)
rsi = if (timeframe.isminutes and timeframe.period == '1')
    rsi(close, 14)
else if (timeframe.isminutes and timeframe.period == '15')
    rsi(close, 14)
else 
    rsi(close, 30)
    
macd = fastMA - slowMA
macdOverExtended = if (hideMacdMatch == true)
    0
else if (timeframe.isdaily)
    100 + (high - macd) / high * 100 <= 191.5 ? 100 + (high - macd) / high * 100 : 0
else if (timeframe.isminutes and timeframe.period == '240') // DONE
    if (rsi > 60)
        100 + (high - macd) / high * 100 <= 196.8 ? 100 + (high - macd) / high * 100 : 0
    else
        100 + (high - macd) / high * 100 >= 203 ? 100 + (high - macd) / high * 100 : 0
else if (timeframe.isminutes and timeframe.period == '15') // DONE
    if (rsi > 60)
        100 + (high - macd) / high * 100 <= 199 ? 100 + (high - macd) / high * 100 : 0
    else
        100 + (high - macd) / high * 100 >= 201 ? 100 + (high - macd) / high * 100 : 0
else if (timeframe.isminutes and timeframe.period == '60') // TODO
    if (rsi > 60)
        100 + (high - macd) / high * 100 <= 198 ? 100 + (high - macd) / high * 100 : 0
    else
        100 + (high - macd) / high * 100 >= 201.8 ? 100 + (high - macd) / high * 100 : 0
else if (timeframe.isminutes and timeframe.period == '1') // DONE
    if (rsi > 60)
        100 + (high - macd) / high * 100 <= 199.8 ? 100 + (high - macd) / high * 100 : 0
    else
        100 + (high - macd) / high * 100 >= 200.5 ? 100 + (high - macd) / high * 100 : 0
else
    0

backgroundColorByRSI = if (timeframe.isminutes)

    rsiValueHigh = if (timeframe.period == '1')
        70
    else if (timeframe.period == '5')
        70
    else if (timeframe.period == '15')
        70
    else if (timeframe.period == '30')
        72
    else if (timeframe.period == '60')
        69
    else if (timeframe.period == '240')
        70
    else
        na
    
    rsiValueHigher = if (timeframe.period == '1')
        74
    else if (timeframe.period == '5')
        72
    else if (timeframe.period == '15')
        73
    else if (timeframe.period == '30')
        74
    else if (timeframe.period == '60')
        72
    else if (timeframe.period == '240')
        74  
    else
        na
    
    rsiValueLow = if (timeframe.period == '1')
        30
    else if (timeframe.period == '5')
        35
    else if (timeframe.period == '15')
        32
    else if (timeframe.period == '30')
        37
    else if (timeframe.period == '60')
        34
    else if (timeframe.period == '240')
        42
    else
        na
    
    rsiValueLower = if (timeframe.period == '1')
        27
    else if (timeframe.period == '5')
        33
    else if (timeframe.period == '15')
        30
    else if (timeframe.period == '30')
        32
    else if (timeframe.period == '60')
        32
    else if (timeframe.period == '240')
        40
    else
        na

    if (rsi >= rsiValueHigher and macdOverExtended > 0)
        if (showMacdMatchOnly)
            color.new(color.red, 40)
        else
            color.new(color.orange, 40)
    else if (rsi >= rsiValueHigh and macdOverExtended > 0)
        if (showMacdMatchOnly)
            color.new(color.red, 40)
        else
            color.new(color.orange, 40)
    else if (showMacdMatchOnly == false and rsi >= rsiValueHigher)
        color.new(color.red, 40)
    else if (showMacdMatchOnly == false and rsi >= rsiValueHigh)
        color.new(color.red, 70)
    else if (rsi <= rsiValueLower and macdOverExtended > 0)
        if (showMacdMatchOnly)
            color.new(color.green, 40)
        else
            color.new(color.blue, 40)
    else if (rsi <= rsiValueLow and macdOverExtended > 0)
        if (showMacdMatchOnly)
            color.new(color.green, 40)
        else
            color.new(color.blue, 40)
    else if (showMacdMatchOnly == false and rsi <= rsiValueLower)
        color.new(color.green, 40)
    else if (showMacdMatchOnly == false and rsi <= rsiValueLow)
        color.new(color.green, 70)
else if (timeframe.isdaily)
    rsiValueHigh = 72
    
    rsiValueHigher = 77  
    
    rsiValueLow = 30
    
    rsiValueLower = 30

    if (rsi >= rsiValueHigher and macdOverExtended > 0)
        if (showMacdMatchOnly)
            color.new(color.red, 40)
        else
            color.new(color.orange, 40)
    else if (rsi >= rsiValueHigh and macdOverExtended > 0)
        if (showMacdMatchOnly)
            color.new(color.red, 40)
        else
            color.new(color.orange, 40)
    else if (showMacdMatchOnly == false and rsi >= rsiValueHigher)
        color.new(color.red, 40)
    else if (showMacdMatchOnly == false and rsi >= rsiValueHigh)
        color.new(color.red, 70)
    else if (showMacdMatchOnly == false and rsi <= rsiValueLower)
        color.new(color.green, 40)
    else if (showMacdMatchOnly == false and rsi <= rsiValueLow)
        color.new(color.green, 70)
else if (timeframe.isweekly)
    rsiValueHigh = 83
    
    rsiValueHigher = 90
    
    rsiValueLow = 44
    
    rsiValueLower = 42

    if (showMacdMatchOnly == false and rsi >= rsiValueHigher)
        color.new(color.red, 40)
    else if (showMacdMatchOnly == false and rsi >= rsiValueHigh)
        color.new(color.red, 70)
    else if (showMacdMatchOnly == false and rsi <= rsiValueLower)
        color.new(color.green, 40)
    else if (showMacdMatchOnly == false and rsi <= rsiValueLow)
        color.new(color.green, 70)
else
    na
bgcolor(color=backgroundColorByRSI)