//@magicksean
//@version=4
study(title="Magicks (e)mas Indicator", shorttitle="Magick", overlay=true, format=format.price, resolution="610", resolution_gaps= false)

///Group A (Magick MAs)
// 21ema, 50ema, 11ema

//Calculate
ema= ema(ohlc4,21)
ema2= ema(ohlc4,50)

//Draw EMAs
plot(ema, linewidth=1, color=#999999, title="Fast")
plot(ema2, linewidth=1, color=#333333, title="Mid")

///Group B (Support Band)
// 365(e)ma

//Calculate Ribbon
EMA = ema(close, 365)
SMA = sma(close, 365)

//Draw Ribbon

p1 = plot(EMA, color=#000000, title="R(EMA)", transp = 45, linewidth = 1)
p2 = plot(SMA, color=#000000, title="R(SMA)", transp = 45, linewidth = 1)
fill(p1, p2, transp = 87, color = EMA > SMA ? color.green : #990000)

///Group C (Trend Channel)
// sma 365*2 , ema 111

//Calculate MAs
High = sma(ohlc4, 365)*2
Low = ema(ohlc4, 111)

//Plot MAs
plot(High, linewidth=3, color=#000000, title="Trend High")
plot(Low, linewidth=2, color=#000000, title="Trend Low")
